version: '3.8'

services:
  backend:
    build:
      context: ./mysite
    container_name: django-backend
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "mysite.asgi:application"]
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    networks:
      - shared-network
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongodb:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENSIM_ROS_HOST=opensimrt_ros_
      - OPENSIM_ROS_PORT=9090

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/newfolder
    ports:
      - "4000:4000"
    networks:
      - shared-network
    environment:
      - DJANGO_HOST=django-backend
      - DJANGO_PORT=8000
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  node_modules: {}


