version: '3.8'

services:
  backend:
    build:
      context: ./mysite
    container_name: django-backend
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "mysite.asgi:application"]
    volumes:
      - ./mysite:/app
      - /home/yilin/softdev/docker-opensimrt/Data/tmp0:/app/data  # Mount the host directory to /app/data inside the container
    ports:
      - "8000:8000"
    networks:
      - shared-network
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongodb:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENSIM_ROS_HOST=opensimrt_ros_
      - OPENSIM_ROS_PORT=9090

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shared-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo_data:/data/db

networks:
  shared-network:

volumes:
  node_modules: {}
  mongo_data:


